finetune_weights: /mnt/projects/ObjectDetection/weights/yolo_weights/ORIG/yolov5s.pt

project: /mnt/projects/ObjectDetection/weights/yolo_weights
name: Fall_v5s_conv

cfg: models/yolov5s_conv.yaml
data: fall/Fall.yaml
hyp: data/hyp.finetune.yaml
epochs: 200
batch_size: 128
img_size: [736, 416]
device: '0,1,2,3'
test_task: val
workers: 16

conf_thresh: 0.2
iou_thresh: 0.4